import type { PullRequestArtifact } from "./types";

const KIND_GLYPH: Record<string, string> = {
  added: "A",
  modified: "M",
  deleted: "D",
};

/** Render a PR artifact as GitHub-flavoured markdown, ready to paste into a PR. */
export function artifactToMarkdown(artifact: PullRequestArtifact): string {
  const lines: string[] = [];
  const section = (title: string, items: string[]) => {
    lines.push(`## ${title}`, "");
    for (const item of items) lines.push(`- ${item}`);
    lines.push("");
  };

  lines.push(`# ${artifact.title}`, "", artifact.summary, "");

  section("Implementation plan", artifact.implementationPlan);

  lines.push("## Files changed", "");
  for (const f of artifact.filesChanged) {
    lines.push(
      `- \`${KIND_GLYPH[f.kind] ?? "?"}\` \`${f.path}\` (+${f.additions}/-${f.deletions}) — ${f.summary}`,
    );
  }
  lines.push("");

  section("Testing plan", artifact.testingPlan);
  section("Risks", artifact.risks);

  lines.push("## Reviewer checklist", "");
  for (const item of artifact.reviewerChecklist) lines.push(`- [ ] ${item}`);
  lines.push("");

  section("Rollback plan", artifact.rollbackPlan);

  lines.push(
    "---",
    `_Generated by Forge — Software Engineering Agent Platform._`,
  );

  return lines.join("\n");
}
